### ISSUE TITLE
README should explain advantages over using `super`

### ISSUE THREAD

**Issue by benjaminoakes** [ContinuityControl/tiny_sweeper#1]
I haven't a huge amount of time to digest `TinySweeper` yet, but one of the first things that came to my mind was "how is this better than just overriding the setter?"  I don't think I'm the only one who would think that, so let's make sure the advantages are clear in the README.  (The advantages over `ActiveRecord` callbacks are explained well, though.)

To make it concrete, why wouldn't we just do this?

``` ruby
def attr=(val)
  super(val.strip.downcase)
end
```

As an analogy, you could use a `memoize` gem...

``` ruby
def expensive_op
  lots_of_expensive_operations
end

memoize :expensive_op
```

Or you could do this, which doesn't require a library:

``` ruby
def expensive_op
  @expensive_op ||= lots_of_expensive_operations
end
```

**Comment by ZachBeta** [comment]
Agreed.

Seeing more complex use cases would help clarify that this is more advantageous.

**Comment by danbernier** [comment]
Let's work through some here, before we add them to the README.

One benefit is that the manual approach doesn't scale. If you have 20 fields, you have to redefine 20 methods, and get them all correct. But we can extend TinySweeper so this works:

``` ruby
sweep(:heads, :shoulders, :knees, :toes) { |part| part.whatever }
```

That syntax isn't valid in TinySweeper yet, so it's not in the README - but it might be a good addition.

Another benefit is that it separates concerns: data-scrubbing from actual logic. If you have a writer method like this:

``` ruby
def property=(value)
  return if value.nil?                        # sweeping
  value.strip!                                # sweeping
  between = mappings.fetch(value, 'default')  # logic
  super(between.capitalize)                   # logic
end
```

In that case, using an abstraction helps. (You could extract the guts into another method, but that's just pushing the dirt around.)

What do you think, convincing?

**Comment by treznick** [comment]
The case for abstraction convinces me, but I'm easily convinced.

On Mon, Feb 9, 2015 at 9:21 PM, Dan Bernier notifications@github.com
wrote:

> Let's work through some here, before we add them to the README.
> 
> One benefit is that the manual approach doesn't scale. If you have 20
> fields, you have to redefine 20 methods, and get them all correct. But we
> can extend TinySweeper so this works:
> 
> sweep(:heads, :shoulders, :knees, :toes) { |part| part.whatever }
> 
> That syntax isn't valid in TinySweeper yet, so it's not in the README -
> but it might be a good addition.
> 
> Another benefit is that it separates concerns: data-scrubbing from actual
> logic. If you have a writer method like this:
> 
> def property=(value)
>   return if value.nil?                        # sweeping
>   value.strip!                                # sweeping
>   between = mappings.fetch(value, 'default')  # logic
>   super(between.capitalize)                   # logicend
> 
> In that case, using an abstraction helps. (You could extract the guts into
> another method, but that's just pushing the dirt around.)
> 
> What do you think, convincing?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/tiny_sweeper/issues/1#issuecomment-73632706
> .

## 

Tom Reznick
Junior Software Engineer, Continuity
914-519-8966

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity Control.

**Comment by benjaminoakes** [comment]
I get where you're headed with sweeping vs logic, but there's a fine line between those two... A better example is probably warranted.

---

One thing that could be a clear win would be something like this:

``` ruby
sweep :heads, :shoulders, :knees, :toes, with: WhateverSweeper
# or maybe...
sweep :heads, :shoulders, :knees, :toes, &WhateverSweeper
```

That way you could have a reusable `WhateverSweeper`

``` ruby
class WhateverSweeper
  def something(val)
    # ...
  end
end

# or
class WhateverSweeper
  # some variation on this... I swear there's a way to do this with `def call(val)`
  def to_proc
    lambda { |val| val.whatever }
  end
end
```

...which could have specs:

``` ruby
describe WhateverSweeper do
  context 'weird case #1' do
    # ...
  end

  context 'weird case #2' do
    # ...
  end
end
```

**Comment by danbernier** [comment]
@benjaminoakes re: a fine line between sweeping and logic: if, in a given case, the line is unclear, I'd probably opt to not use TinySweeper, so the story is all told together. It's like using guard statements: the line between a guard statement and regular logic is sometimes unclear - but sometimes it's not, and so we use them.

I think the more compelling argument is scaling. Generally, sweeping is something we don't care about, or think about - it's something we take for granted. A good example is stripping user's names: every time you see "Doe , John", because his last name is "Doe ", you say "ahh, crap, we forgot to strip." Then you think: nuts, I have to override, like, 10 attributes on User. No one wants to do that. TinySweeper should make it easy for you:

```
sweep(:first_name, :middle_initial, :last_name, :title, :email, 
      :address1, :address2, :city, :state, :zip, &:strip)
```

---

Aside from passing multiple attributes, I think your `&WhateverSweeper` example either already works, or isn't far off. I like that Class#to_proc style, and more broadly, letting people pass an arbitrary object that responds to `:call`. Let's make sure it works well.

The other thing your example brought to mind is: should TinySweeper provide some sweeping routines that people can use? "strip, but also nil blanks" is an obvious choice, because it's a common need, but it's not a method we can just send to a String. And now that I'm thinking about it, I think your `&WhateverSweeper` example shows how to do it: TinySweeper can come with handy methods, maybe in a module, so you can do something like:

``` ruby
sweep(:first_name, :middle_initial, :last_name, TinySweeper.strip_and_nil_blanks)
```

That way, common cases are provided, and will be spec'd in TinySweeper, so you don't have to.

**Comment by danbernier** [comment]
@benjaminoakes take a look at this: 9e95e41e62d7f1033bc8cf187fcf29cb02197459

Do you think it addresses your concerns about explaining the benefits?

**Comment by benjaminoakes** [comment]
Yeah, it definitely helps.  Thanks!

It feels like we should include a `to_proc` example, because that might not be too obvious to people.  That would definitely lend its way to pull requests if we supplied a place for these "to_proc" classes (or whatever) to live.

**Comment by danbernier** [comment]
Cool, np!

I don't know (yet) if TinySweeper should be a repository of sweeping routines. I've thought about it, but I'm not sure.

For now, I'll close this issue. The `to_proc` thing bears thinking through.

**Comment by benjaminoakes** [comment]
I know what you mean, I think.  However, a major part of the value of open sourcing this is to get contributions, and making that easy is always good.  :smile: Wouldn't it be nice to find out someone else added a sweeper that we need?

**Comment by danbernier** [comment]
Yeah, but - for example - rails doesn't want a PR with my models added, so
I don't have to add them in my project. That's the distinction I'm trying
to make correctly.

On Tue, Mar 3, 2015 at 10:40 AM, Ben Oakes notifications@github.com wrote:

> I know what you mean, I think. However, a major part of the value of open
> sourcing this is to get contributions, and making that easy is always good. [image:
> :smile:] Wouldn't it be nice to find out someone else added a sweeper
> that we need?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/tiny_sweeper/issues/1#issuecomment-76969275
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity Control.

**Comment by benjaminoakes** [comment]
I'd say the model analogy isn't quite right; this is more like adding common validations to the libary.

What you bring up is an interesting difference in philosophy that can make or break an OSS project.  Consider the difference between Linux (which is monolithic and gets a billion contributions) and xnu (the OSX microkernel, which rarely -- if ever -- gets any external contributions, although it's also OSS).  It seems like a contradiction, but sometimes monolithic projects are better for OSS.  [The Cathedral and the Bazaar](http://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar) talks about this, I think...  And I've found it to be true with contributions to Maid as well.

That said, you can always start big and then break pieces apart.  But let's have that be a problem first.  :smile:

**Comment by danbernier** [comment]
I think I'm replying too quickly to make myself clear. (Busy day.) And we should probably have this discussion somewhere other than an unrelated issue ticket. That said, here we are, so:

I'm not opposed to building in sweepers. But I don't want to _require_ it - people should be able to use their own sweep routine, without having to wait for their PR to be merged. Include-everything and include-nothing are the poles of the question, and I bring them up not because I'm taking those positions, but to map the terrain, to make the question clear.

What I want to do is find the right point along the spectrum. I don't know, right this minute, where that is, or what it looks like. I want to think about it, and pick something good.

**Comment by benjaminoakes** [comment]
Yeah, let's talk outside this issue.  My stance really isn't quite so polar.

**Comment by ZachBeta** [comment]
This thread needs more polar bears!
![AWW](http://media.giphy.com/media/1298kcxnGcfoXe/giphy.gif)

**Comment by benjaminoakes** [comment]
![black bear](http://media.giphy.com/media/mqUgLEIaHf680/giphy.gif)

Like that?  It's a polar opposite, right?

**Comment by danbernier** [comment]
omg this thread just improved 9000%.

On Thu, Mar 5, 2015 at 2:33 PM, Ben Oakes notifications@github.com wrote:

> [image: black bear]
> https://camo.githubusercontent.com/019d0ff8999870db6b3e85cc615fa983e8d870f9/687474703a2f2f6d656469612e67697068792e636f6d2f6d656469612f6d7155674c45496148663638302f67697068792e676966
> 
> Like that? It's a polar oppposite, right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinuityControl/tiny_sweeper/issues/1#issuecomment-77434796
> .

## 

## 

---

This email and all files transmitted with it are intended solely for use by 
the intended recipient.  Any other use is prohibited.  If you received this 
email in error, please notify the sender, delete the email and destroy all 
attachments.  Opinions and ideas expressed herein are solely those of the 
sender, and may not reflect the official position of Continuity.
